export const AGENTS = [
  {
    id: 'topic-generator',
    name: 'Research Topic Generator',
    nameTh: 'ผู้สร้างหัวข้อวิจัย',
    description: 'Generate aviation research topics, evaluate novelty, and identify research gaps',
    icon: '🎯',
    color: 'from-blue-500 to-cyan-500',
    capabilities: ['Topic Generation', 'Novelty Evaluation', 'Gap Detection', 'Domain Matching'],
    category: 'discovery',
  },
  {
    id: 'literature-review',
    name: 'Literature Review Agent',
    nameTh: 'ผู้ทบทวนวรรณกรรม',
    description: 'Search and synthesize academic literature from Scopus, WoS, Semantic Scholar',
    icon: '📚',
    color: 'from-purple-500 to-indigo-500',
    capabilities: ['Scopus Search', 'WoS Search', 'Thematic Analysis', 'Literature Matrix'],
    category: 'discovery',
  },
  {
    id: 'citation-mapping',
    name: 'Citation Mapping Agent',
    nameTh: 'ผู้วิเคราะห์การอ้างอิง',
    description: 'Build citation graphs, co-citation analysis, and bibliometric visualization',
    icon: '🕸️',
    color: 'from-teal-500 to-green-500',
    capabilities: ['Citation Graph', 'Co-citation Analysis', 'Bibliometric', 'Keyword Clustering'],
    category: 'analysis',
  },
  {
    id: 'research-gap',
    name: 'Research Gap Agent',
    nameTh: 'ผู้ตรวจสอบช่องว่างงานวิจัย',
    description: 'Detect underexplored areas and identify contradictory findings in aviation research',
    icon: '🔍',
    color: 'from-orange-500 to-yellow-500',
    capabilities: ['Gap Detection', 'Contradiction Finder', 'Future Opportunities', 'Trend Analysis'],
    category: 'analysis',
  },
  {
    id: 'framework-builder',
    name: 'Conceptual Framework Agent',
    nameTh: 'ผู้สร้างกรอบแนวคิด',
    description: 'Design conceptual frameworks with hypotheses, mediators, and moderators',
    icon: '🏗️',
    color: 'from-pink-500 to-rose-500',
    capabilities: ['Framework Design', 'Hypothesis Generation', 'TAM/UTAUT/SERVQUAL', 'Diagram Builder'],
    category: 'design',
  },
  {
    id: 'questionnaire',
    name: 'Questionnaire Builder',
    nameTh: 'ผู้สร้างแบบสอบถาม',
    description: 'Generate validated Likert-scale questionnaires in Thai and English',
    icon: '📋',
    color: 'from-violet-500 to-purple-500',
    capabilities: ['Likert Scale', 'Bilingual Thai-EN', 'Construct Validation', 'Export Word/Excel'],
    category: 'design',
  },
  {
    id: 'data-analysis',
    name: 'Data Analysis Agent',
    nameTh: 'ผู้วิเคราะห์ข้อมูล',
    description: 'Perform SEM, CFA, PLS-SEM, regression analysis with APA-style output',
    icon: '📊',
    color: 'from-emerald-500 to-cyan-500',
    capabilities: ['SEM/CFA', 'PLS-SEM', 'Regression', 'APA Tables'],
    category: 'analysis',
  },
  {
    id: 'paper-writing',
    name: 'Paper Writing Agent',
    nameTh: 'ผู้เขียนบทความ',
    description: 'Generate complete thesis chapters and research papers in APA 7th edition',
    icon: '✍️',
    color: 'from-sky-500 to-blue-500',
    capabilities: ['Chapter 1-5', 'Scopus Paper', 'APA 7th Edition', 'Conference Paper'],
    category: 'writing',
  },
  {
    id: 'publication',
    name: 'Publication Agent',
    nameTh: 'ผู้สนับสนุนการตีพิมพ์',
    description: 'Match journals, check similarity, validate references, and draft cover letters',
    icon: '📰',
    color: 'from-amber-500 to-orange-500',
    capabilities: ['Journal Matching', 'Similarity Check', 'Cover Letter', 'Reviewer Response'],
    category: 'writing',
  },
  {
    id: 'thesis-supervisor',
    name: 'Thesis Supervisor Agent',
    nameTh: 'อาจารย์ที่ปรึกษาดิจิทัล',
    description: 'Review thesis chapters, check consistency, and provide advisor-level feedback',
    icon: '👨‍🏫',
    color: 'from-red-500 to-pink-500',
    capabilities: ['Chapter Review', 'Consistency Check', 'Feedback', 'Improvement Suggestions'],
    category: 'supervision',
  },
  {
    id: 'sem-expert',
    name: 'SEM/CFA Expert Agent',
    nameTh: 'ผู้เชี่ยวชาญ SEM/CFA',
    description: 'Validate CFA models, check CR/AVE/HTMT, and generate SmartPLS/AMOS outputs',
    icon: '🔬',
    color: 'from-indigo-500 to-blue-500',
    capabilities: ['CFA Validation', 'CR/AVE/HTMT', 'SmartPLS', 'AMOS Syntax'],
    category: 'analysis',
  },
  {
    id: 'aviation-knowledge',
    name: 'Aviation Knowledge Agent',
    nameTh: 'ผู้เชี่ยวชาญด้านการบิน',
    description: 'Deep knowledge of ICAO, IATA, aviation regulations, and industry standards',
    icon: '✈️',
    color: 'from-blue-600 to-sky-400',
    capabilities: ['ICAO Standards', 'IATA Regulations', 'Airport Management', 'Air Cargo'],
    category: 'domain',
  },
]

export const AVIATION_MODULES = [
  { id: 'airline', name: 'Airline Management', icon: '✈️', topics: 45 },
  { id: 'airport', name: 'Airport Management', icon: '🏢', topics: 38 },
  { id: 'cargo', name: 'Air Cargo & Logistics', icon: '📦', topics: 32 },
  { id: 'safety', name: 'Aviation Safety', icon: '🛡️', topics: 29 },
  { id: 'technology', name: 'Aviation Technology', icon: '💻', topics: 41 },
  { id: 'sustainability', name: 'Aviation Sustainability', icon: '🌱', topics: 24 },
  { id: 'passenger', name: 'Passenger Experience', icon: '👥', topics: 36 },
  { id: 'economics', name: 'Air Transport Economics', icon: '📈', topics: 31 },
]

export const RESEARCH_FRAMEWORKS = [
  'TAM', 'UTAUT', 'UTAUT2', 'SERVQUAL', 'SERVPERF', 'ECT', 'TOE',
  'RBV', 'Social Identity Theory', 'Grounded Theory', 'TPB', 'TRA',
  'Kano Model', 'Balanced Scorecard', 'Blue Ocean Strategy',
]

export const STATS_METHODS = [
  'Descriptive Statistics', 'Reliability Analysis (Cronbach Alpha)',
  'Exploratory Factor Analysis (EFA)', 'Confirmatory Factor Analysis (CFA)',
  'Structural Equation Modeling (SEM)', 'PLS-SEM',
  'Multiple Regression', 'Mediation Analysis', 'Moderation Analysis',
  'ANOVA', 'Independent t-test', 'Correlation Analysis',
]
